### ISSUE TITLE
Link to docs in readme?

### ISSUE THREAD

**Issue by rauschma** [01alchemist/TurboScript#1]
Suggestion: link to the following page in README.md: https://dump.01alchemist.com/2016/12/31/future-webhpc-parallel-programming-with-javascript-the-new-era-about-to-begin/ (functions as a sort-of minimal documentation explaining what this project is about).

**Comment by nidin** [comment]
Useful links added to readme. Detailed documentation will follow after full asm.js emitter validation completed

**Comment by rauschma** [comment]
👍
