### ISSUE TITLE
New Playground

### ISSUE THREAD

**Issue by MaxGraey** [01alchemist/TurboScript#102]
I'm working now on new playground for TurboScript, AssemblyScript and may be speedy.js. And I thinking of best way to integrate compiler back-end for TurboScript. I see previous playground implemented in user browser and I like this approach because I can publish in this case to Github Pages, but if I choose to server-sided compiler I could make databases and other useful stuff. In that case I need great and free node.js hosting. What are you thinking about it?

![Screenshot](https://www.dropbox.com/s/h3gb5v4thr57fkl/screenshot-playground.jpg?raw=1)

**Comment by dcodeIO** [comment]
Note that the final product will use the TurboScript compiler instead of asc :)

**Comment by MaxGraey** [comment]
Yes, user could choose between AssemblyScript and Turboscript :)

**Comment by nidin** [comment]
Here is a list
* https://zeit.co/pricing (max single file size 1MB / total storage 1GB)
* https://www.heroku.com/pricing (limited resources)
* https://aws.amazon.com/free/ (complicated setup)

**Comment by MaxGraey** [comment]
Thanks, I decided use frontend compiler yet. But bay be in future I switch to dedicated server

**Comment by nidin** [comment]
@MaxGraey Is the new playground hosted in github?

**Comment by nidin** [comment]
@MaxGraey  never mind, I found it from your pinned repos. I can contribute to spin up TurboScript compilation.

**Comment by MaxGraey** [comment]
@nidin If you integrate turboscript It will be awesome. I had some problems with resolving tbs files

**Comment by nidin** [comment]
Sure, I will look in to it today.

**Comment by MaxGraey** [comment]
[compile routine for turboscript](https://github.com/MaxGraey/Assembleash/blob/master/src/Containers/EditorContainer.js#L219)

Just implement basic things with default compiler options. Every compiler has its own set of settings, so still need some refactoring. I will do this later.

[turboscript source directory](https://github.com/MaxGraey/Assembleash/tree/master/public/compilers/TurboScript). Every compiler lazy loading from it's own public directory.
