### ISSUE TITLE
Improve QuickStart guidance

### ISSUE THREAD

**Issue by pannous** [01alchemist/TurboScript#110]
awesome project! 

newcomers still need two clicks to find this: https://github.com/01alchemist/TurboScript/wiki/Quick-start  and then they need further clicks to find out how actual example code looks like.

 suggestion: put it on the main readme, together with some small example.

PS: greetings to Munich! 𓃹

**Comment by nidin** [comment]
Sure, I am on it. 👍

**Comment by nidin** [comment]
Basic examples added to README
