### ISSUE TITLE
This simple class code compile, but incorrectly

### ISSUE THREAD

**Issue by MaxGraey** [01alchemist/TurboScript#12]
Example:

```ts

class Foo {
   a: float32;
   constructor(a: float32): Foo {
       this.a = a;
   }
}

export function newFoo(foo: float32): Foo {
    return new Foo(foo);
}

export function destroyFoo(foo: Foo): void {
    delete foo;
}

```

**Comment by nidin** [comment]
which target ? asm.js or wasm? or both.
Try adding return this inside constructor

**Comment by MaxGraey** [comment]
Yes, adding ```return this``` compile correctly. So I think it's just limitation current implementation^ but generating error in compile time but to generate an error still stands

**Comment by nidin** [comment]
Ideally there is no return type or return statement needed in constructor. It's a limitation/bug or to be precise it's a lazy implementation of constructor. I am renaming the title of the issue

**Comment by nidin** [comment]
This issue is fixed. now constructor syntax is aligned with typescript.

**Comment by MaxGraey** [comment]
Wow, I see you implement also return ```this``` as type for constructors according to last PRs. Good job!
