### ISSUE TITLE
Can't use latest TurboScript in browser (1.0.2-beta)

### ISSUE THREAD

**Issue by MaxGraey** [01alchemist/TurboScript#125]
```window.turboscript``` is undefined

**Comment by nidin** [comment]
It seems working for me in Assembleash.

**Comment by MaxGraey** [comment]
Currently I use scriptjs for dynamic loading. I try loadjs, systemjs and all the same issue - turboscript load, but not visible in window scope. I can't figure out what is problem

**Comment by nidin** [comment]
Changed webpack library bundle type from umd to var. now its working. but its a problem with scriptjs.

**Comment by MaxGraey** [comment]
Thanks!
