### ISSUE TITLE
Custom Memory Access?

### ISSUE THREAD

**Issue by facekapow** [01alchemist/TurboScript#126]
I was wondering if it's possible to override the runtime's memory management. See, since TurboScript compiles to WebAssembly, I'm looking to integrate it into an OS that uses V8 (called runtime.js) and I'd like to use TurboScript to simplify memory access (JavaScript doesn't have pointers or structs or any of the myriad of great memory management features TurboScript has). The only problem is, TurboScript is restricted to WebAssembly's contained memory. Is there any way to get around that? Maybe a way to override the memory access on TurboScript's runtime? If not, is it possible for me to implement it?

This is a great project, btw. Hope it continues to grow!

**Comment by RangerMauve** [comment]
@facekapow I think you're able to dynamically increase memory for a WebAssembly context and pass buffers in an out

**Comment by facekapow** [comment]
@RangerMauve Thanks for your response, but what I meant was providing access to native memory. i.e. passing in specific areas of memory, or even giving it access to all the memory on the system. I can do it if I'm able to pass in ArrayBuffers as memory. I just don't know how (or if) that's possible.

**Comment by MaxGraey** [comment]
WebAssembly run in the same sandbox as well as javascript and hasn't direct access to system memory. Only one difference between js and wasm - last one use linear preallocated memory without GC.

**Comment by facekapow** [comment]
@MaxGraey Well, the thing is, the OS (runtime.js) provides native memory access to JavaScript via ArrayBuffers. I can get direct system memory access from the OS in JavaScript. Given that, could I pass that ArrayBuffer to WebAssembly so it can work with it instead of its sandboxed memory?

**Comment by RangerMauve** [comment]
You could definately pass in an ArrayBuffer as an argument to functions exported from a WASM module.

Consider reading the API docs [on mdn](https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API)

**Comment by RangerMauve** [comment]
It won't work the same way as the sandboxed memory since that's managed by WASM, but you could have WASM modify the memory in the array buffer

**Comment by dcodeIO** [comment]
The way this currently works is to specify a memory instance on instantiation of the module, and to import and use that as its memory. The only way to do this dynamically otherwise is to copy to the existing memory.

**Comment by facekapow** [comment]
Ok, thanks to everyone who helped, I'll figure something out 👍

**Comment by winksaville** [comment]
Some quick thoughts:

*) Provide an import that does peek/poke or higher level functionality.
*) Consider creating something other than a JavaScript based runtime, there
is nothing that's JavaScript specific in the spec, AFAICT. I'm interested
in doing something like this.
*) Create a WebAssembly to native compiler, one way to do this might be to
create a wast/wasm to native code generator for llvm.

**Comment by nidin** [comment]
@facekapow You can pass independently created wasm memory instance to a wasm module. You Need to provide same native memory access via wasm memory. May it will be easy with SharedArrayBuffer. I guess shared memory will be accessible from JavaScript and Wasm.
