### ISSUE TITLE
It seems 1.0.5-beta broken in browser

### ISSUE THREAD

**Issue by MaxGraey** [01alchemist/TurboScript#129]

**Comment by nidin** [comment]
I reverted webpack library target to umd. bcoz "var" library target was not working in nodejs. 
I am investigating umd load problem with scriptjs

**Comment by MaxGraey** [comment]
It will be perfect! Now I use static linked scripts for TS and AS

**Comment by nidin** [comment]
I guess, this might be the problem 
![image](https://user-images.githubusercontent.com/198246/27772380-5554f750-5f61-11e7-8631-fdac11940fbb.png)

**Comment by nidin** [comment]
are you using rawgit.com?

**Comment by MaxGraey** [comment]
I use rawgit.com of course.
Check tests my [script.js repo](https://github.com/MaxGraey/script.js/blob/master/tests/tests.js). This test pass in vanilla js but fail inside react.js environment=(

**Comment by MaxGraey** [comment]
Modern browsers ignore MIME type. But recommend use ```application/javascript```. Never mind, script always load successfully.Main problem with assignment to global scope

**Comment by nidin** [comment]
I am closing this issue as this cannot be fixed from this repo.

**Comment by MaxGraey** [comment]
sure
