### ISSUE TITLE
Unable to use unsigned right shift operator

### ISSUE THREAD

**Issue by dignifiedquire** [01alchemist/TurboScript#137]
When trying to use the `>>>` operator I get a compiler error saying ` ERROR: Unexpected '>'`, `>>` compiles fine.

**Comment by nidin** [comment]
**Not implemented**
TurboScript was a prototype and I am no logger updating this repo instead I am working on a language specification for TurboScript [here](https://github.com/TurboScriptLang/spec/blob/master/spec.md) once the spec completed. I will start working on the fresh implementation.
