### ISSUE TITLE
Is this only for browser or I can use in Node.js?

### ISSUE THREAD

**Issue by ohenepee** [01alchemist/TurboScript#138]

**Comment by RangerMauve** [comment]
The latest version of Node has experimental support for WASM. Details [here](http://thecodebarbarian.com/getting-started-with-webassembly-in-node.js.html)

**Comment by nidin** [comment]
Yes, it is also available in Node.js however This repository is not maintaining. You may try.
[AssemblyScript ](https://github.com/AssemblyScript/assemblyscript) which is similar to TurboScript.

**Comment by ohenepee** [comment]
Thanks
