### ISSUE TITLE
Module declaration error

### ISSUE THREAD

**Issue by mikcsabee** [01alchemist/TurboScript#141]
When I try to compile the following code ([source](https://github.com/TurboScriptLang/spec/blob/master/spec.md#32-declarations-and-dynamic-linking)) : 

```
declare module console {
    function log(value:int32):void
}
```

I got the following error:
```
ERROR: Expected '(' but found identifier
    function log(value:int32):void
             ~~~
```

**Comment by nidin** [comment]
@mikcsabee The latest spec is not yet implemented. I am not developing TurboScript for now. Please check [AssemblyScript](https://github.com/AssemblyScript/assemblyscript) which I am contributing.
