### ISSUE TITLE
Slack Invitation

### ISSUE THREAD

**Issue by andrewfluck** [01alchemist/TurboScript#143]
Hey I'm really interested in this project. Could you add me to slack? andrewtfluck@gmail.com

**Comment by ColinEberhardt** [comment]
https://github.com/01alchemist/TurboScript/issues/142

**Comment by andrewfluck** [comment]
🙈

**Comment by MaxGraey** [comment]
@andrewfluck 
I advise you to pay attention to [AssemblyScript](https://github.com/AssemblyScript/assemblyscript) which has similar goals.

**Comment by andrewfluck** [comment]
ok sounds 👍 :)

**Comment by nidin** [comment]
Hi @andrewfluck, We are no longer investing time on this project, at least for now.  Like Max said follow  AssemblyScript which is similar. I may restart TurboScript when WebGPU is ready and it will be pure parallel programming platform.

**Comment by MaxGraey** [comment]
@nidin din I think make sense turn repo to ready only mode while project in friezed status. What you think?

**Comment by nidin** [comment]
@MaxGraey That make sense 👍
