### ISSUE TITLE
User wants to use generic data types with classes

### ISSUE THREAD

**Issue by nidin** [01alchemist/TurboScript#2]
**What?**
User wants to have generic data type as parameters for classes and functions

**How?**
Implement generic parameters for classes
```typescript
class className<T>{
}

**Comment by winksaville** [comment]
v2?

**Comment by nidin** [comment]
Generics types for classes are already implemented but generics functions
are not implemented. May be we should split it in to two  issues.

**Comment by winksaville** [comment]
Agreed
