### ISSUE TITLE
Slack button says administrator has not enabled email signups.

### ISSUE THREAD

**Issue by jpambrun** [01alchemist/TurboScript#27]
Slack says 'This team's administrator has not enabled email signups' which makes the button a bit useless.

Also, I really want this project to succeed. After spending a lot of time on a performance intensive JS app, this would be like a dream come true.

**Comment by nidin** [comment]
Oops! Let me check.

**Comment by nidin** [comment]
You need an invitation to join slack. open a ticket with your email address. I will make it happen.

**Comment by jpambrun** [comment]
My email is on my github profile.
