### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by suulnnka** [01alchemist/TurboScript#4]
1.need npm install -g lite-server typescript ts-node ?
2.run npm run build , src/parser.ts:636 error
3.run bash lib/tc.sh, lib/tc.sh:12&17 error
4.run lite-server, http://localhost:4202/playground/index.html , Output: "ReferenceError: TURBO_PATH is not defined"

how to use it ?

how to define Array\<Int32\>?

**Comment by nidin** [comment]
@suulnnka you can now use `npm install -g turboscript` 
and use `tc test.tbs --asmjs --out test.asm.js`
