### ISSUE TITLE
User wants exponented float literals

### ISSUE THREAD

**Issue by MaxGraey** [01alchemist/TurboScript#81]
**What?**
User wants to have exponent declaration literal for float numbers.

**How?**
```ts
let a: float64 = -1.0e-01;
let t: float64 = .5e+8;
```

**Comment by nidin** [comment]
This enhancement added to support benchmarks :)

**Comment by MaxGraey** [comment]
This is not very huge problem, we can always bring it to non-exponent format manually.

**Comment by nidin** [comment]
No worries, It was an easy addition.
